#!/usr/bin/python
import os
import sys
import logging
import logging.config

sys.path.insert(0, os.path.dirname(__file__) or '.')
"""
# add the repository root to the path (add candlepin package to the scope)
sys.path.insert(0, os.environ.get('OPENSHIFT_REPO_DIR', '..'))

PY_DIR = os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "python")

virtenv = PY_DIR + '/virtenv/'

PY_CACHE = os.path.join(virtenv,
                        'lib',
                        os.environ['OPENSHIFT_PYTHON_VERSION'],
                        'site-packages')

os.environ['PYTHON_EGG_CACHE'] = os.path.join(PY_CACHE)
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    exec(open(virtualenv).read(), dict(__file__=virtualenv))
except IOError:
    pass

# set up logging
logging_conf_file = "{0}/logging.conf".format(
    os.environ['OPENSHIFT_REPO_DIR'])
backup = os.getcwd()
os.chdir(os.path.join(os.environ['OPENSHIFT_HOMEDIR'], "app-root"))
logging.config.fileConfig(logging_conf_file)
os.chdir(backup)
"""
from ethel import app as application
